### ISSUE TITLE
Ordering system

### ISSUE THREAD

**Issue by Blinky-Keys** [Weeby-Feet/Hot-Grills#3]
Need a way to display pending orders to the player that doesn't clog the screen. Something like a line of notes at the top of the screen that disappear when the player completes and order and remain if they serve an order incorrectly.

**Comment by Blinky-Keys** [comment]
Order system is almost working. Have to resolve a couple of null reference and off by one bugs still.

**Comment by Weeby-Feet** [comment]
Orders are now functioning as expected.

**Comment by Blinky-Keys** [comment]
Orders are now functioning as expected.
